# Generated by Django 5.2.8 on 2025-11-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_Name', models.CharField(blank=True, max_length=55, null=True)),
                ('cust_Phn', models.IntegerField(blank=True, null=True)),
                ('Booking_Date', models.DateField()),
                ('Booking_on', models.DateField(auto_now=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventapp.event')),
            ],
        ),
    ]
