# Generated by Django 5.2.8 on 2025-11-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booking_Date',
            new_name='booking_date',
        ),
    ]
